### ISSUE TITLE
Voxel.js Feedback

### ISSUE THREAD

**Issue by crossingthesarchasm** [RPG-Research/bcirpg#12]
Leave feedback for voxel.js below

**Comment by PersonGuyGit** [comment]
Voxel.Js is confusing. I cannot figure out how to exactly download it for use. 

There are over 10 repos on the Github, so it is difficult to find a runable application. Will look into this again at a later date

**Comment by rpgresearch** [comment]
On Sat, 11 Jul 2020 11:41:35 -0700
Luke Gebbink <notifications@github.com> wrote:

> Voxel.Js is confusing. I cannot figure out how to exactly download it
> for use. 
> 
> There are over 10 repos on the Github, so it is difficult to find a
> runable application. Will look into this again at a later date
> 


with the .js I'm guessing maybe it is meant to be web/server based
perhaps, rather than an installed client?

-- 
--RPG Research Staff

RPG Research is a 501(c)3 non-profit charitable organization providing
research and community services. https://www.rpgresearch.com
info@rpgresearch.com
1312 North Monroe, Suite #114
Spokane, Washington 99218, US.
Spokane Local Number: (509) 608-7630
Toll-free: (833) RPG-INFO (774-4636)

**Comment by d-zilla** [comment]
Yes, it seems like you need to download node.js and run the game from the command line. Is it safe to assume that we can write that off as a con? i.e. a more complicated requirement to run and play for the general audience compared to the other games.

**Comment by crossingthesarchasm** [comment]
Feedback period closed
